java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	1	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	2	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	3	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	4	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	5	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	6	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	7	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	8	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	9	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	10	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	11	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	12	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	13	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	14	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	15	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	16	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	17	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	18	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	19	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	20	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	21	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	22	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	23	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	24	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	25	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	26	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	27	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	28	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	29	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	30	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	31	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	32	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	33	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	34	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	35	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	36	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	37	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	38	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	39	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	40	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	41	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	42	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	43	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	44	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	45	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	46	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	47	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	48	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	49	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	50	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	51	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	52	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	53	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	54	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	55	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	56	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	57	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	58	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	59	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	60	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	61	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	62	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	63	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	64	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	65	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	66	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	67	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	68	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	69	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	70	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	71	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	72	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	73	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	74	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	75	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	76	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	77	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	78	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	79	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	80	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	81	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	82	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	83	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	84	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	85	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	86	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	87	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	88	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	89	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	90	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	91	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	92	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	93	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	94	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	95	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	96	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	97	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	98	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	99	-novis
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	100	-novis
