java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	1	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	2	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	3	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	4	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	5	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	6	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	7	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	8	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	9	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	10	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	11	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	12	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	13	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	14	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	15	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	16	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	17	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	18	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	19	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	20	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	21	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	22	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	23	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	24	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	25	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	26	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	27	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	28	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	29	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	30	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	31	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	32	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	33	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	34	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	35	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	36	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	37	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	38	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	39	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	40	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	41	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	42	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	43	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	44	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	45	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	46	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	47	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	48	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	49	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	50	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	51	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	52	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	53	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	54	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	55	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	56	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	57	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	58	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	59	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	60	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	61	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	62	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	63	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	64	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	65	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	66	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	67	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	68	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	69	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	70	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	71	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	72	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	73	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	74	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	75	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	76	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	77	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	78	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	79	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	80	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	81	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	82	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	83	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	84	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	85	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	86	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	87	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	88	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	89	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	90	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	91	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	92	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	93	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	94	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	95	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	96	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	97	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	98	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	99	-novis >> out.txt
java -jar FragileMirrorsVis.jar -exec FragileMirrors.exe -seed 	100	-novis >> out.txt
