java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	1	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	2	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	3	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	4	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	5	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	6	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	7	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	8	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	9	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	10	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	11	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	12	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	13	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	14	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	15	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	16	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	17	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	18	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	19	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	20	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	21	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	22	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	23	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	24	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	25	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	26	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	27	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	28	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	29	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	30	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	31	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	32	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	33	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	34	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	35	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	36	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	37	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	38	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	39	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	40	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	41	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	42	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	43	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	44	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	45	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	46	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	47	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	48	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	49	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	50	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	51	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	52	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	53	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	54	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	55	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	56	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	57	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	58	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	59	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	60	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	61	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	62	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	63	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	64	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	65	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	66	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	67	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	68	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	69	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	70	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	71	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	72	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	73	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	74	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	75	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	76	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	77	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	78	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	79	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	80	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	81	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	82	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	83	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	84	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	85	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	86	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	87	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	88	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	89	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	90	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	91	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	92	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	93	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	94	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	95	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	96	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	97	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	98	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	99	 -novis >>nul
java -jar SnowCleaningVis.jar -exec SnowCleaning -delay 0 -seed 	100	 -novis >>nul